name: zoomrad
description: A new Flutter project.

publish_to: 'none'

version: 2.1.359

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.20
  firebase_core: ^1.20.0
  shared_preferences: ^2.0.15
  lottie: ^1.4.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/ic_success.png
    - assets/lottie/
  fonts:
    - family: mont_bold
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
    - family: mont_medium
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: mont_regular
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
    - family: mont_semibold
      fonts:
        - asset: assets/fonts/montserrat_semibold.ttf
